# -*- coding: utf-8 -*-
"""SMSShow

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kvhHPsc3iFnmeQoj5Tx4TUOWGWXfHNZv
"""

!pip install streamlit

import streamlit as st
import pickle as pic
import nltk
from nltk.corpus import stopwords as sw
from sklearn.feature_extraction.text import TfidfVectorizer
import string as sr
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
nltk.download('punkt')
tfidf = TfidfVectorizer()

def tars_text(text):
  text = text.lower()
  text = nltk.word_tokenize(text)

  y = []  #Removing special chars
  for i in text:
    if i.isalnum():
      y.append(i)

  text = y[:]
  y.clear()

  for i in text: #Removing stop and punctuations
    if i not in sw.words('english') and i not in sr.punctuation:
      y.append(i)

  text = y[:]
  y.clear()

  for i in text:
    y.append(ps.stem(i))

  return " ".join(y)

tfidf = pic.load(open('/content/vectorizer (1).pkl','rb'))
model = pic.load(open('/content/model (1).pkl','rb'))

input_sms = st.text_input('Enter Message')

#1.Preprocssing the text
trans_text = tars_text(input_sms)

#2.Vectorize
vector_input = tfidf.transform([trans_text])

#3.Predict
result = model.predict(vector_input)[0]

#4.Display
if result == 1:
  st.header('Its A SPAM MESSAGE!!!!!!!!')
else:
  st.header('Genuine Message :)')

!streamlit run SpamEmail.py

st.title('Nightmare of SPams!')

!streamlit run /usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py